---
title: "Functions Lab (Wednesday)"
author: "Ruth Vergara Reyes"
date: "3/24/2021"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    theme: journal
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = TRUE)
```

# Intro 

For this lab weeks lab homework I will be making two functions.

# Load Libraries 
```{r,message=FALSE}
library(tidyverse)
library(here)
library(calecopal)
```

# Load Data

For this lab I will be using chem data.
```{r,message=FALSE}
Chem_data <- read_csv(here("week_8","data","chemicaldata_maunalua.csv"))

view(Chem_data)
```

# Making The Non-plot Function 
```{r}
Cel_to_Fah <- function(temp_C) { 
  temp_F <- (temp_C*(9/5))+32 
  return(temp_F)
}                           ### This function converts temperature in Celsius to Fahrenheit
```

### Testing out the function
```{r}
Cel_to_Fah(56)

Cel_to_Fah(102)
```


# Making the Plot Function
```{r}

ChemPlot<-function(data = Chem_data, x, y, Time = "Day"){
cal <- cal_palette("lake",3, type = "discrete")   ### my color palette
  if(Time == "Day"){
    data%>%
      filter(Time == "Day")%>%
    ggplot(aes(x = {{x}}, y = {{y}} , color = Site))+
      geom_point()+                              ### type of plot it will be 
      scale_color_manual("Site", values = cal)+  ### color palette used
      theme_minimal()                                 ### theme of plot
}
else{
  data %>%
    filter(Time== "Night")
    ggplot(aes(x = {{x}}, y = {{y}} , color = Site))+
      geom_point()+                               ### type of plot 
      scale_color_manual("Site", values = cal)+   ### color scale 
      theme_minimal()                                  ### plot theme
}
}

```


### Testing the function
```{r}
# The following plot shows variations of pH based on "Zone"
ChemPlot(x = Zone, y = pH)+
    labs(x = "Zone",   
       y = "pH Scale")        ### Labels for the axis    
#  The following plot shows variations of the temperature(C) during the tide_time of day
ChemPlot(x = Tide_time, y = Temp_in)+
    labs(x = "Time of Day)", 
       y = "Temperature (C)") ### Labels for the axis

```


